### PR TITLE
add map.html

### PR DESCRIPTION
**Pull request by jyx11011**
Try adding a page to show a map and several markers.

### CODE REVIEW

**Comment by LISH0038** [comment]
Look good to me :)
I'm thinking to move the js functions into another js file because we may have more than one map and we may share some of the functions. We can merge them first then do more refactoring in other PRs.

**Review by LISH0038 — APPROVED** [review]

**Comment by BenMQ** [comment]
> Look good to me :)
> I'm thinking to move the js functions into another js file because we may have more than one map and we may share some of the functions. We can merge them first then do more refactoring in other PRs.

Yea! it's a good idea to separate the HTML and JS code :D

**Review by BenMQ — APPROVED** [review]

**Review by calebmah — CHANGES_REQUESTED** [review]
There's some inconsistency in the indentation of some of the code. Some parts seem to be indented with tabs, I think we standardized to use 2 spacing indents. Also some lines like lines 6, 18, 31, 39 for example are indented strangely.

**Review by Jay-kew — CHANGES_REQUESTED** [review]
It would be good if you can rectify the indentations as mentioned by Caleb :)

**Pull request merged**
